### ISSUE TITLE
Erfassung auf vergangene Tage fehlerhatft

### ISSUE THREAD

**Issue by Anaktuvuk** [limenet/just-in-time#110]
URL:

## Checks - Teil 1

- [x] Ist das Problem nicht bereits gemeldet?
- [x] Gibt es keine offene must-have User Story, die dieses Problem betrifft?

## Erwartetes Verhalten

1. Am 18.07.17 wurde eine Zeit erfasst für den 10.07.17 (zB. 3 H). Dabei wurde das Feld "Datum bis" angepasst auf 10.07.17

## Tatsächliches Verhalten

1.Der Wert wurde verteilt vom 10.07. bis 18.07.
Auch wenn das Bis-Datum nachträglich korrigiert wird, wird wieder 18.07. gespeichert

## Schritte um das Problem zu reproduzieren

1. Wert auf vergangenes Datum  erfassen.

## Checks - Teil 2

- [x] Hat die Issue das Label `bug`?
- [x] Ist ein Priority-Label gesetzt?

---

**Sind die Checks 1 und 2 nicht erfüllt (checked), wird die Issue nicht bearbeitet.**

**Comment by limenet** [comment]
> Wert auf vergangenes Datum erfassen.

Und ich dachte, ich könnte hier etwas schummeln 😉

Danke!
