### ISSUE TITLE
US1: Datenbankmodell

### ISSUE THREAD

**Issue by limenet** [limenet/just-in-time#23]
bezieht sich auf #1

**Comment by limenet** [comment]
Zwischenstand von @pajazmuh und @tannerap 

[DBModell.pdf](https://github.com/limenet/just-in-time/files/853524/DBModell.pdf)

**Comment by limenet** [comment]
@tannerap @pajazmuh bitte Diagramm gemäss ist-Zustand der DB aktualisieren. Danke!

**Comment by pajazmuh** [comment]
[DBModell .pdf](https://github.com/limenet/just-in-time/files/875299/DBModell.pdf)
