### ISSUE TITLE
US8: Planning

### ISSUE THREAD

**Issue by limenet** [limenet/just-in-time#44]
#8

**Comment by Anaktuvuk** [comment]
Wir stellen uns in etwa folgende Charts vor: 

1) Verlauf Tag/Woche: Verteilung von "Support" und "Projekten", bzw. andere Haupttätigkeiten/Gruppen
2) Chart z.B. "Support": Verteilung der Stunden auf Just CH, Just Deutschland, Just International. Sinngemäss gleiches für ein Projekt (Aufteilung nach Schulung, Konzept, Go Live, etc.)
3) bei 2) "Support" wäre auch interessant, eine Verteilung zu Modulen wie "SAP Lager, SAP Vertrieb, Netzwerkwerk, Subsystem xy, etc.

Je nach Lösung ist ein Drill-down von z.B. Quartal auf Monat auf Woche auf Tag nice-to-have. 
Bei fix festgelegten Zeiträumen wäre wohl Woche und Monat zu wählen.

**Comment by Anaktuvuk** [comment]
Habe das Thema mit dem IT-Leiter besprochen. 
Ergänzung:
Wenn es machbar ist, wäre eine Sicht auf ein gesamtes Projekt interessant. Also nicht nur aus Sicht eines Mitarbeiters ("zeige mir meine Aufwände zum Projekt xy"), sondern auch die gesamten Aufwände zu einem Projekt ("zeige die Aufwände aller beteiligten Mitarbeiter/Aufwände zum Projekt xy").

**Comment by meyersi117** [comment]
Ergänzung:
Wenn es machbar ist, wäre eine Sicht auf ein gesamtes Projekt interessant. Also nicht nur aus Sicht eines Mitarbeiters ("zeige mir meine Aufwände zum Projekt xy"), sondern auch die gesamten Aufwände zu einem Projekt ("zeige die Aufwände aller beteiligten Mitarbeiter/Aufwände zum Projekt xy").

**Comment by meyersi117** [comment]
Hier eine erste, grobe Skizze für das Konfigurieren und anzeigen eines Report. 

Entspricht diese in etwa den Erwartungen?
(hellblau sind jeweils einfache Buttons, für simples und schnelles Konfigurieren)

[Reporting_Skizze.pdf](https://github.com/limenet/just-in-time/files/919846/Reporting_Skizze.pdf)

**Comment by Anaktuvuk** [comment]
Ja, ich denke schon. Das passt.

**Comment by Anaktuvuk** [comment]
Hallo Silvan, die Charts ev. als Doughnut chart darstellen, was meinst du?
![image](https://cloud.githubusercontent.com/assets/3395987/25018096/6f898c86-2086-11e7-95d8-d9d956ffc004.png)

**Comment by meyersi117** [comment]
Front-end für das Reproting ist als dev-preview verfügbar und kann am Sprint vom 25. April 2017 besprochen werden.
