### ISSUE TITLE
US9: Planning

### ISSUE THREAD

**Issue by limenet** [limenet/just-in-time#47]
#9

**Comment by haem** [comment]
Die Daten aus dem heute eingesetzten Stundenerfassungssystem werden täglich an das zentrale MIS übergeben. Die Daten werden in einem Stagingbereich vorbereitet und dann im MIS verarbeitet. Es handelt sich um Stamm- und Bewegungstabellen. Im Anhang sind sämtliche Tabellen aufgelistet, die übergeben werden.

Zukünftig benötigen wir sämtliche Bewegungsdaten, also alle verfügbaren Datenelemente, in Form eines Datenexportes.  Die Daten sollten zur automatisierten Verarbeitung von uns abgeholt werden können.  
Die zugehörigen Stammdatentabellen können ebenfalls mitgeliefert werden. 

Um die Daten in unserem MIS verarbeiten zu können wird die Konvertierung von JUST übernommen. Die Auswertungen im MIS werden in den nächsten Monaten überarbeitet werden. 

[Rapportwerte - Analyse IST.zip](https://github.com/limenet/just-in-time/files/943967/Rapportwerte.-.Analyse.IST.zip)

**Comment by Anaktuvuk** [comment]
In einer ersten Phase ist ein Download Button (wie Export/pikapp) ausreichend. Nach Möglichkeit Excel, sonst CSV.
Später soll ein automatisierter Weg (FTP o.ä.) realisiert werden.
