### ISSUE TITLE
Mitarbeiter können nicht zugeordnet werden (dem neuen Projekt)

### ISSUE THREAD

**Issue by Anaktuvuk** [limenet/just-in-time#73]
URL:https://www.justintime.work/projects/101/edit

## Checks - Teil 1

- [x] Ist das Problem nicht bereits gemeldet?
- [x] Gibt es keine offene must-have User Story, die dieses Problem betrifft?

## Erwartetes Verhalten

1. Mitarbeiter zuordnen.

## Tatsächliches Verhalten

1. Funktion nicht möglich

## Schritte um das Problem zu reproduzieren

1. Siehe Projekt SAP EHP8 Upgrade.

## Checks - Teil 2

- [x] Hat die Issue das Label `bug`?
- [x] Ist ein Priority-Label gesetzt?

---

**Sind die Checks 1 und 2 nicht erfüllt (checked), wird die Issue nicht bearbeitet.**

**Comment by Anaktuvuk** [comment]
Mitarbeiter können nun ausgewählt werden, werden aber nicht gespeichert

**Comment by Anaktuvuk** [comment]
MA können nicht zugeordnet werden, bzw. einmal ging es, kann aber nicht reproduziert werden

**Comment by limenet** [comment]
Liegt an #91
