### ISSUE TITLE
Projekt steht in der Zeiterfassung nicht zur Auswahl bereit

### ISSUE THREAD

**Issue by Anaktuvuk** [limenet/just-in-time#74]
URL:https://justintime.work/projecttaskuser/create

## Checks - Teil 1

- [x] Ist das Problem nicht bereits gemeldet?
- [x] Gibt es keine offene must-have User Story, die dieses Problem betrifft?

## Erwartetes Verhalten

1. Das Projekt "SAP EHP..." steht nicht zur Verfügung beim Erfassen von Zeiten

## Tatsächliches Verhalten

1. 

## Schritte um das Problem zu reproduzieren

1. 

## Checks - Teil 2

- [x] Hat die Issue das Label `bug`?
- [x] Ist ein Priority-Label gesetzt?

---

**Sind die Checks 1 und 2 nicht erfüllt (checked), wird die Issue nicht bearbeitet.**

**Comment by limenet** [comment]
Liegt wahrscheinlich an #73
