### ISSUE TITLE
Erfassen einer Zeit erzeugt Fehlermeldung

### ISSUE THREAD

**Issue by Anaktuvuk** [limenet/just-in-time#75]
URL:https://justintime.work/projecttaskuser/create

## Checks - Teil 1

- [x] Ist das Problem nicht bereits gemeldet?
- [x] Gibt es keine offene must-have User Story, die dieses Problem betrifft?

## Erwartetes Verhalten

1. Zeiterfassung kann verbucht werden oder
2. eine eindeutige Fehlermeldung wird ausgegeben

## Tatsächliches Verhalten

1. Whoops, looks like something went wrong.

## Schritte um das Problem zu reproduzieren

1. Zeit erfassen (alle Felder wurden befüllt beim Test)

## Checks - Teil 2

- [x] Hat die Issue das Label `bug`?
- [x] Ist ein Priority-Label gesetzt?

---

**Sind die Checks 1 und 2 nicht erfüllt (checked), wird die Issue nicht bearbeitet.**

**Comment by limenet** [comment]
Nicht das Erstellen ist das Problem, sondern das Anzeigen des gerade erstellten Eintrages. Dies ist "unauthorized".

**Comment by limenet** [comment]
Es lag an einem Durcheinander von Stamm- und Pivot-Tabellen-IDs.
