### ISSUE TITLE
Sortieransicht

### ISSUE THREAD

**Issue by pajazmuh** [limenet/just-in-time#76]
URL:

## Checks - Teil 1

- [x] Ist das Problem nicht bereits gemeldet?
- [x] Gibt es keine offene must-have User Story, die dieses Problem betrifft?

## Erwartetes Verhalten

1. Sortiersymbol sollte klar erkennbar zur einer Spalte gehören

## Tatsächliches Verhalten

1.Verwirrende Darstellung

## Schritte um das Problem zu reproduzieren

1. Auf Projekte gehen.

## Checks - Teil 2

- [x] Hat die Issue das Label `bug`?
- [x] Ist ein Priority-Label gesetzt?

---

**Sind die Checks 1 und 2 nicht erfüllt (checked), wird die Issue nicht bearbeitet.**

**Comment by limenet** [comment]
Liegt am zu hohen "Neu"-Button
