### ISSUE TITLE
Projekt kann nicht gelöscht werden

### ISSUE THREAD

**Issue by Anaktuvuk** [limenet/just-in-time#85]
URL:https://justintime.work/projects/103/edit

## Checks - Teil 1

- [x] Ist das Problem nicht bereits gemeldet?
- [x] Gibt es keine offene must-have User Story, die dieses Problem betrifft?

## Erwartetes Verhalten

1. Projekt wird nicht mehr angezeigt
2.
3.

## Tatsächliches Verhalten

1. es wird 2x gefragt, ob das Projekt gelöscht werden soll
2. nach 2 x JA, wird ein weisser Screen angezeigt, Projekt ist nicht gelöscht
3.

## Schritte um das Problem zu reproduzieren

1.
2.
3.

## Checks - Teil 2

- [x] Hat die Issue das Label `bug`?
- [x] Ist ein Priority-Label gesetzt?

---

**Sind die Checks 1 und 2 nicht erfüllt (checked), wird die Issue nicht bearbeitet.**

**Comment by limenet** [comment]
Das Feature ist backend-seitig noch nicht implementiert...

**Comment by limenet** [comment]
Duplikat von #80
