### ISSUE TITLE
Stammdatenbezeichnung falsch

### ISSUE THREAD

**Issue by Anaktuvuk** [limenet/just-in-time#88]
URL:

## Checks - Teil 1

- [x] Ist das Problem nicht bereits gemeldet?
- [x] Gibt es keine offene must-have User Story, die dieses Problem betrifft?

## Erwartetes Verhalten

1. "Projektgruppe" an Stelle von "Projekte"
## Tatsächliches Verhalten

1. Bezeichnung ist ungenau/falsch

## Schritte um das Problem zu reproduzieren
![image](https://cloud.githubusercontent.com/assets/3395987/26109112/c3548532-3a4e-11e7-9c6c-3af0caa8fe1d.png)

## Checks - Teil 2

- [x] Hat die Issue das Label `bug`?
- [x] Ist ein Priority-Label gesetzt?

---

**Sind die Checks 1 und 2 nicht erfüllt (checked), wird die Issue nicht bearbeitet.**

**Comment by limenet** [comment]
Fix ist bereits unterwegs!
