### ISSUE TITLE
Projektliste: Spalten sortierbar machen wie bei Mitarbeiter, etc.

### ISSUE THREAD

**Issue by Anaktuvuk** [limenet/just-in-time#89]
URL: https://justintime.work/projects
## Checks - Teil 1

- [x] Ist das Problem nicht bereits gemeldet?
- [x] Gibt es keine offene must-have User Story, die dieses Problem betrifft?

## Erwartetes Verhalten

1. Liste sortierbar machen

## Tatsächliches Verhalten

1.
2.
3.

## Schritte um das Problem zu reproduzieren

1.
2.
3.

## Checks - Teil 2

- [x] Hat die Issue das Label `bug`? (enhancement)
- [x] Ist ein Priority-Label gesetzt?

---

**Sind die Checks 1 und 2 nicht erfüllt (checked), wird die Issue nicht bearbeitet.**

**Comment by limenet** [comment]
Gleich wie bei #88 - Issue war 1 Minute zu früh 😄
