### ISSUE TITLE
Task dem Projekt hinzufügen geht nicht

### ISSUE THREAD

**Issue by Anaktuvuk** [limenet/just-in-time#90]
URL:

## Checks - Teil 1

- [x] Ist das Problem nicht bereits gemeldet?
- [x] Gibt es keine offene must-have User Story, die dieses Problem betrifft?

## Erwartetes Verhalten

1. Einem bestehenden oder neuen Projekt sollen Tasks hinzugefügt werden
2. (Löschen Tasks ist OK).

## Tatsächliches Verhalten

1. geht nicht
## Schritte um das Problem zu reproduzieren

1.
2.
3.

## Checks - Teil 2

- [x] Hat die Issue das Label `bug`?
- [x] Ist ein Priority-Label gesetzt?

---

**Sind die Checks 1 und 2 nicht erfüllt (checked), wird die Issue nicht bearbeitet.**

**Comment by limenet** [comment]
#91
