### ISSUE TITLE
Zeitaufwand bei "Projekt anlegen" soll kein Mussfeld sein

### ISSUE THREAD

**Issue by Anaktuvuk** [limenet/just-in-time#92]
URL:

## Checks - Teil 1

- [x] Ist das Problem nicht bereits gemeldet?
- [x] Gibt es keine offene must-have User Story, die dieses Problem betrifft?

## Erwartetes Verhalten

1. Der geplante Zeitaufwand für ein Projekt ist meistens nicht bekannt (z.B. bei Unterhalt).
2. Somit soll das Feld kein Mussfeld sein

## Tatsächliches Verhalten

1. Eingabe zwingend

## Schritte um das Problem zu reproduzieren

1. Neues Projekt anlegen

## Checks - Teil 2

- [x] Hat die Issue das Label `bug`?
- [x] Ist ein Priority-Label gesetzt?

---

**Sind die Checks 1 und 2 nicht erfüllt (checked), wird die Issue nicht bearbeitet.**

**Comment by limenet** [comment]
Danke für die Info, ist so angepasst!
