### ISSUE TITLE
Hinzugefügte Tasks können nicht gelöscht werden (Berechtigung)?

### ISSUE THREAD

**Issue by Anaktuvuk** [limenet/just-in-time#93]
URL:

## Checks - Teil 1

- [x] Ist das Problem nicht bereits gemeldet?
- [x] Gibt es keine offene must-have User Story, die dieses Problem betrifft?

## Erwartetes Verhalten

1. Tasks zu einem Projekt müssen gelöscht werden können

## Tatsächliches Verhalten

1. bestehende Tasks können gelöscht werden
2. Neue (heute?) angelegte Tasks können nicht gelöscht werden (Löschbutton inaktiv)

## Schritte um das Problem zu reproduzieren

1.
2.
3.

## Checks - Teil 2

- [x] Hat die Issue das Label `bug`?
- [x] Ist ein Priority-Label gesetzt?

---

**Sind die Checks 1 und 2 nicht erfüllt (checked), wird die Issue nicht bearbeitet.**

**Comment by limenet** [comment]
Der Löschbutton sollte nur inaktiv sein, wenn bereits Zeiten darauf gebucht sind... Danke für die Info.
