### ISSUE TITLE
Neuer Mitarbeiter: Sollarbeitszeit mit Dezimalstellen

### ISSUE THREAD

**Issue by Anaktuvuk** [limenet/just-in-time#94]
URL:

## Checks - Teil 1

- [x] Ist das Problem nicht bereits gemeldet?
- [x] Gibt es keine offene must-have User Story, die dieses Problem betrifft?

## Erwartetes Verhalten

1. Bei einem MA muss die Sollarbeitszeit z.B. mit 8.2 H erfasst werden können

## Tatsächliches Verhalten

1. Es können nur ganze H erfasst werden
2.
3.

## Schritte um das Problem zu reproduzieren

1.
2.
3.

## Checks - Teil 2

- [x] Hat die Issue das Label `bug`?
- [x] Ist ein Priority-Label gesetzt?

---

**Sind die Checks 1 und 2 nicht erfüllt (checked), wird die Issue nicht bearbeitet.**

**Comment by limenet** [comment]
Kommt die Fehlermeldung vom Browser?

Habe einen Fix gemacht, kannst du bitte kurz prüfen?

**Comment by Anaktuvuk** [comment]
ist nun OK
