### ISSUE TITLE
Ändern einer erfassten Zeit: Feld 'Projekt' ist leer

### ISSUE THREAD

**Issue by Anaktuvuk** [limenet/just-in-time#95]
URL:

## Checks - Teil 1

- [x] Ist das Problem nicht bereits gemeldet?
- [x] Gibt es keine offene must-have User Story, die dieses Problem betrifft?

## Erwartetes Verhalten

1. Wird eine erfasste Zeit geändert, so sollen alle bereits erfassten Werte vorgeschlagen werden.
2. Danach können Werte geändert werden, Im Normalfall werden die erfassten Zeiten geändert, oder der Eintrag wird ganz gelöscht.

## Tatsächliches Verhalten

1. Feld 'Projekt' ist leer, alle anderen bereits erfassten Werte werden angezeigt

## Schritte um das Problem zu reproduzieren

1.
2.
3.

## Checks - Teil 2

- [x] Hat die Issue das Label `bug`?
- [x] Ist ein Priority-Label gesetzt?

---

**Sind die Checks 1 und 2 nicht erfüllt (checked), wird die Issue nicht bearbeitet.**

**Comment by limenet** [comment]
> oder der Eintrag wird ganz gelöscht.

momentan noch nicht möglich, kommt bald

Bug ist gefixt. Danke!
