### ISSUE TITLE
Nach "Mitarbeiter ändern" kommt log-in

### ISSUE THREAD

**Issue by Anaktuvuk** [limenet/just-in-time#97]
URL:

## Checks - Teil 1

- [x] Ist das Problem nicht bereits gemeldet?
- [x] Gibt es keine offene must-have User Story, die dieses Problem betrifft?

## Erwartetes Verhalten

1. Nach dem Speichern einer MA-Änderung soll wieder die MA-Liste (o.ä.) angezeigt werden.
2.
3.

## Tatsächliches Verhalten

1. Nach dem Speichern einer Änderung (z.B. Soll Arbeitszeit) wird das Login angezeigt, danach die Infos inkl. Berechtigungen zum Mitarbeiter
2.
3.

## Schritte um das Problem zu reproduzieren

1.
2.
3.

## Checks - Teil 2

- [x] Hat die Issue das Label `bug`?
- [x] Ist ein Priority-Label gesetzt?

---

**Sind die Checks 1 und 2 nicht erfüllt (checked), wird die Issue nicht bearbeitet.**

**Comment by limenet** [comment]
Da funktioniert uns das Laravel-eigene Authentifizierungssystem wohl rein... Danke für die Info!

**Comment by limenet** [comment]
Kannst du es mal in einem Incognito-Modus Fenster (`Ctrl+Shift+N`) versuchen (dort funktioniert es)? Evtl. macht Lastpass hier Probleme.

**Comment by Anaktuvuk** [comment]
chrome Incogito: funktioniert.
firefox (keine Lastpass Integration): funktioniert.
chrome "normal" mit Lastpass: Loginscreen

**Comment by limenet** [comment]
Das liegt an Lastpass, da kann ich nichts machen.
