### ISSUE TITLE
Reporting Chart 1 und 3, Laufende Woche

### ISSUE THREAD

**Issue by Anaktuvuk** [limenet/just-in-time#98]
URL:

## Checks - Teil 1

- [x] Ist das Problem nicht bereits gemeldet?
- [x] Gibt es keine offene must-have User Story, die dieses Problem betrifft?

## Erwartetes Verhalten

1. Bei den Charts 1 und 3 wäre ein Umschalten von "letzter Woche" auf "aktuelle Woche" wünschenswert.
2. Falls Umschalten momentan zu viel Aufwand: Lieber "laufende Woche" anzeigen
3.

## Tatsächliches Verhalten

1.
2.
3.

## Schritte um das Problem zu reproduzieren

1.
2.
3.

## Checks - Teil 2

- [x] Hat die Issue das Label `bug`? (fast)
- [x] Ist ein Priority-Label gesetzt?

---

**Sind die Checks 1 und 2 nicht erfüllt (checked), wird die Issue nicht bearbeitet.**

**Comment by limenet** [comment]
Zusammen mit #99 : es sind jeweils die letzten sieben Tage, die angezeigt werden. Was ist gewünscht?

1. die letzten 7 Tage
1. die aktuelle Woche (Montag bis heute)
1. die letzte Woche (Montag bis Sonntag)

**Comment by Anaktuvuk** [comment]
Prio 1: Die aktuelle Woche (MO bis heute).
Prio 2: Die letzte Woche (MO bis SO)


hansmetzler.me



2017-05-23 9:29 GMT+02:00 Linus Metzler <notifications@github.com>:
